[package]
name = "keeble"
version = "0.1.0"
authors = ["Jason Wall <jason@thejayvm.ca>"]

[dependencies]
usb-device = "0.2.7"
cortex-m-rt = "0.7.3"
nrf52840-hal = "0.16.0"
panic-semihosting = "0.6.0"
